[package]
name = "DankRustBot"
version = "0.1.0"
authors = ["Simon <33012273+5E7EN@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.3.6"
tokio = { version = "0.2.22", features = ["rt-core", "time", "sync", "macros", "stream"] }
twitch-irc = "0.2.1"